Revert "charger: do not suspend when handling home"
system/core/charger/charger.c:827: error: undefined reference to 'request_suspend'
collect2: error: ld returned 1 exit status
make: *** [out/target/product/maguro/obj/EXECUTABLES/charger_intermediates/LINKED/charger] Error 1
make: *** Waiting for unfinished jobs....


This reverts commit b0d2b0fafcf34d49d6f288010b63f58293d49ba1