adb: Link to libdl manually to avoid build failure on android-build
An outdated build environment results in a host adb build failure
because libcrypto needs libdl, but libdl isn't linked explicitly:
out/host/linux-x86/obj/STATIC_LIBRARIES/libcrypto_static_intermediates/libcrypto_static.a(dso_dlfcn.o):
In function `dlfcn_globallookup':
/mnt/jenkins/workspace/linaro-android_galaxynexus-jb-gcc47-aosp-blob/build/external/openssl/crypto/dso/dso_dlfcn.c:474:
undefined reference to `dlopen'
/mnt/jenkins/workspace/linaro-android_galaxynexus-jb-gcc47-aosp-blob/build/external/openssl/crypto/dso/dso_dlfcn.c:478:
undefined reference to `dlsym'
/mnt/jenkins/workspace/linaro-android_galaxynexus-jb-gcc47-aosp-blob/build/external/openssl/crypto/dso/dso_dlfcn.c:479:
undefined reference to `dlclose'

Change-Id: Ia232430d9f636779db84ff05ae7ece7256be8894
Signed-off-by: Bernhard Rosenkraenzer <Bernhard.Rosenkranzer@linaro.org>